# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require "open-uri";

ActiveRecord::Base.transaction do
  
  User.destroy_all
  demo1 = User.create!(email: 'young1@gmail.com', password: 'password')
  demo2 = User.create!(email: 'young2@gmail.com', password: 'password')
  demo3 = User.create!(email: 'young3@gmail.com', password: 'password')
  demo4 = User.create!(email: 'young4@gmail.com', password: 'password')
  demo5 = User.create!(email: 'young5@gmail.com', password: 'password')




  Artist.destroy_all
  eminem = Artist.create!(name: "Eminem", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/eminem.jpeg" )
  linkinPark = Artist.create!(name: "Linkin Park", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/Linkin-Park.jpg" )
  royOrbison = Artist.create!(name: "Ray Orbison", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/royOrbison.jpg" )
  vanillaIce = Artist.create!(name: "Vanilla Ice", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/Vanilla-ice.jpg" )
  katyPerry = Artist.create!(name: "Katy Perry", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/katyPerry.jpg" )
  ladyGaga = Artist.create!(name: "Lady Gaga", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/ladyGaga.jpg" )
  aHa = Artist.create!(name: "A-Ha", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/aHa.jpg" )
  backStreetBoys = Artist.create!(name: "Backstreet Boys", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/backStreetBoys.jpg" )
  justinBieber = Artist.create!(name: "Justin Bieber", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/justinBieber.jpg" )
  elvisPresley = Artist.create!(name: "Elvis Presley", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/elvisPresley.jpg" )
  boyz2Men = Artist.create!(name: "Boyz 2 Men", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/boyz2men.jpg" )
  theKillers = Artist.create!(name: "The Killers", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/the-killers.png" )
  louisArmstrong = Artist.create!(name: "Louis Armstrong", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/louisArmstrong.jpg" )
  daftPunk = Artist.create!(name: "Daft Punk", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/daftPunk.webp" )
  rihanna = Artist.create!(name: "Rihanna", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/rihanna.jpg" )
  beyonce = Artist.create!(name: "Beyonce", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/beyonce.jpg" )
  theEagles = Artist.create!(name: "The Eagles", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/theEagles.jpg" )
  ledZeppelin = Artist.create!(name: "Led Zeppelin", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/led-zeppelin-1969.jpg" )
  whitneyHouston = Artist.create!(name: "Whitney Houston", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/whitneyHouston.jpg" )
  tupac = Artist.create!(name: "Tupac", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/Tupac.jpg" )
  bobMarley = Artist.create!(name: "Bob Marley", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/bobmarley.jpg" )
  michaelJackson = Artist.create!(name: "Michael Jackson", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson.jpeg" )
  thePolice = Artist.create!(name: "The Police", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/ThePolice.jpg" )
  mcHammer = Artist.create!(name: "MC Hammer", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/mcHammer.jpg" )
  wizKhalifa = Artist.create!(name: "Wiz Khalifa", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/wizkhalifa.jpg" )
  survivor = Artist.create!(name: "Survivor", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/survivor.jpg" )
  theBlackEyedPeas = Artist.create!(name: "The Black Eyed Peas", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/blackEyedPeas.jpg" )
  kellyClarkson = Artist.create!(name: "Kelly Clarkson", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/kelyyClarkson.jpg" )
  adele = Artist.create!(name: "Adele", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/adele.jpg" )
  arethaFranklin = Artist.create!(name: "Aretha Franklin", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/arethaFranklin.JPG" )
  theBeatles = Artist.create!(name: "The Beatles", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/theBeatles.jpg" )
  pharrellWilliams = Artist.create!(name: "Pharrell Williams", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/pharrellWilliams.jpg" )
  luisFonsi = Artist.create!(name: "Luis Fonsi", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/luisFondiu.jpg" )
  spiceGirls = Artist.create!(name: "Spice Girls", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/spice_girls_platform-shoes.jpg" )
  gunsNRoses = Artist.create!(name: "Guns N Roses", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/guns-n-roses-2018.jpg" )
  markRonson = Artist.create!(name: "Mark Ronson", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/markronson.jpeg" )
  celineDion = Artist.create!(name: "Celine Dion", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/celineDion.webp" )
  outkast = Artist.create!(name: "Outkast", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/outkast.png" )
  journey = Artist.create!(name: "Journey", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/journey.jpg" )
  nirvana = Artist.create!(name: "Nirvana", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/Nirvana-4.jpg" )
  beeGees = Artist.create!(name: "Bee Gees", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/beegees.jpg" )
  britneySpears = Artist.create!(name: "Britney Spears", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/Britney-Spears.jpg" )
  acdc = Artist.create!(name: "ACDC", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/acdc.jpg" )
  jimiHendrix = Artist.create!(name: "Jimi Hendrix", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/jimiHendrix.jpg" )
  theRollingStones = Artist.create!(name: "The Rolling Stones", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/theRollingStones.jpg" )
  queen = Artist.create!(name: "Queen", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/queen.jpg" )
  biggieSmalls = Artist.create!(name: "Biggie Smalls", biography: "bio", photo: "https://s3-us-west-1.amazonaws.com/modify-dev/biggieSmalls.jpg" )
  



  Album.destroy_all
  eminem_a1 = Album.create!(title: "Curtain Call", year: 2005, artist_id: eminem.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/curtainCall.png" )
  linkinPark_a1 = Album.create!(title: "Hybrid Theory", year: 2001, artist_id: linkinPark.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/hybridTheory.jpg" )
  royOrbison_a1 = Album.create!(title: "Yo te Amo Maria", year: 1964, artist_id: royOrbison.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/yoTeAmoMaria.jpg" )
  vanillaIce_a1 = Album.create!(title: "Play That Funky Music", year: 1989, artist_id: vanillaIce.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/playThatFunkyMusic.jpg" )
  katyPerry_a1 = Album.create!(title: "One of the Boys", year: 2008, artist_id: katyPerry.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/oneOfTheBoys.jpg" )
  ladyGaga_a1 = Album.create!(title: "The Fame", year: 2008, artist_id: ladyGaga.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/theFame.jpg" )
  aHa_a1 = Album.create!(title: "Hunting High and Low", year: 1984, artist_id: aHa.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/huntingHighAndLow.jpg" )
  backStreetBoys_a1 = Album.create!(title: "Millennium", year: 1998, artist_id: backStreetBoys.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/millennium.jpg" )
  justinBieber_a1 = Album.create!(title: "Purpose", year: 2015, artist_id: justinBieber.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/purpose.jpg" )
  elvisPresley_a1 = Album.create!(title: "Night Mare", year: 1952, artist_id: elvisPresley.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/nightMare.jpg" )
  boyz2Men_a1 = Album.create!(title: "II", year: 1994, artist_id: boyz2Men.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/II.jpg" )
  theKillers_a1 = Album.create!(title: "Smile Like You Mean It", year: 2003, artist_id: theKillers.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/smileLikeYouMeanIt.jpg" )
  louisArmstrong_a1 = Album.create!(title: "Cabaret", year: 1967, artist_id: louisArmstrong.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/cabaret.jpg" )
  daftPunk_a1 = Album.create!(title: "Random Access Memories", year: 2012, artist_id: daftPunk.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/randomAccessMemories.jpg" )
  rihanna_a1 = Album.create!(title: "Good Girl Gone Bad", year: 2007, artist_id: rihanna.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/goodGirlGoneBad.jpg" )
  beyonce_a1 = Album.create!(title: "I Am... Sash Fierce", year: 2008, artist_id: beyonce.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/iAmSashFierce.jpg" )
  theEagles_a1 = Album.create!(title: "Hotel California", year: 1976, artist_id: theEagles.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/hotelCalifornia.jpg" )
  ledZeppelin_a1 = Album.create!(title: "Led Zeppelin IV", year: 1971, artist_id: ledZeppelin.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/ledZeppelinIV.jpg" )
  whitneyHouston_a1 = Album.create!(title: "Whitney", year: 1987, artist_id: whitneyHouston.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/whitney.jpg" )
  tupac_a1 = Album.create!(title: "All Eyez on Me", year: 1995, artist_id: tupac.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/allEyezOnMe.jpg" )
  bobMarley_a1 = Album.create!(title: "Exodus", year: 1977, artist_id: bobMarley.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/exodus.jpg" )
  katyPerry_a2 = Album.create!(title: "Teenage Dream", year: 2010, artist_id: katyPerry.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/teenageDream.jpg" )
  michaelJackson_a1 = Album.create!(title: "Thriller", year: 1982, artist_id: michaelJackson.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/thriller.jpg" )
  thePolice_a1 = Album.create!(title: "Synchronicity", year: 1983, artist_id: thePolice.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/synchronicity.jpg" )
  mcHammer_a1 = Album.create!(title: "Please Hammer, Don't Hurt 'Em", year: 1989, artist_id: mcHammer.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/pleaseHammerDontHurtEm.jpg" )
  wizKhalifa_a1 = Album.create!(title: "Nine Track Mind", year: 2015, artist_id: wizKhalifa.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/nineTrackMind.jpg" )
  eminem_a2 = Album.create!(title: "The Slim Shady LP", year: 1999, artist_id: eminem.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/slimShadyLP.jpg" )
  survivor_a1 = Album.create!(title: "Eye of the Tiger", year: 1982, artist_id: survivor.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/eyeOfTheTiger.jpg" )
  theBlackEyedPeas_a1 = Album.create!(title: "The E.N.D.", year: 2009, artist_id: theBlackEyedPeas.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/theEnd.jpg" )
  kellyClarkson_a1 = Album.create!(title: "Breakaway", year: 2004, artist_id: kellyClarkson.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/breakaway.jpg" )
  adele_a1 = Album.create!(title: "21", year: 2010, artist_id: adele.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/21.jpg" )
  arethaFranklin_a1 = Album.create!(title: "I Never Loved a Man the Way I Love You", year: 1967, artist_id: arethaFranklin.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/iNeverLovedAManTheWayILoveYou.jpeg" )
  theBeatles_a1 = Album.create!(title: "Meet the Beatles", year: 1963, artist_id: theBeatles.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/meetTheBeatles.jpg" )
  pharrellWilliams_a1 = Album.create!(title: "Girl", year: 2013, artist_id: pharrellWilliams.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/girl.jpg" )
  beyonce_a2 = Album.create!(title: "Dangerously in Love", year: 2003, artist_id: beyonce.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/dangerouslyInLove.jpg" )
  luisFonsi_a1 = Album.create!(title: "Viva la Vida", year: 2017, artist_id: luisFonsi.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/vivaLaVida.jpeg" )
  spiceGirls_a1 = Album.create!(title: "Spice", year: 1996, artist_id: spiceGirls.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/spice.jpeg" )
  gunsNRoses_a1 = Album.create!(title: "Appetite for Desctruction", year: 1988, artist_id: gunsNRoses.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/appetiteForDestruction.jpeg" )
  markRonson_a1 = Album.create!(title: "Uptown Special", year: 2014, artist_id: markRonson.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/uptownSpecial.jpg" )
  whitneyHouston_a2 = Album.create!(title: "Jolene", year: 1974, artist_id: whitneyHouston.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/jolene.jpg" )
  celineDion_a1 = Album.create!(title: "Let's Talk About Love", year: 1997, artist_id: celineDion.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/letsTalkAboutLove.jpg" )
  eminem_a3 = Album.create!(title: "8 Mile", year: 2002, artist_id: eminem.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/8Mile.jpg" )
  outkast_a1 = Album.create!(title: "Speakerboxxx/The Love Below", year: 2003, artist_id: outkast.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/speakerboxxxTheLoveBelow.jpg" )
  journey_a1 = Album.create!(title: "Escape", year: 1981, artist_id: journey.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/escape.jpg" )
  nirvana_a1 = Album.create!(title: "Nevermind", year: 1991, artist_id: nirvana.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/nevermind.jpg" )
  beeGees_a1 = Album.create!(title: "Saturday Night Fever", year: 1977, artist_id: beeGees.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/saturdayNightFever.jpg" )
  britneySpears_a1 = Album.create!(title: "...Baby One More Time", year: 1998, artist_id: britneySpears.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/babyOneMoreTime.png" )
  theBeatles_a2 = Album.create!(title: "Revolution", year: 1968, artist_id: theBeatles.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/revolution.jpeg" )
  acdc_a1 = Album.create!(title: "Highway to Hell", year: 1978, artist_id: acdc.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/highwayToHell.jpg" )
  jimiHendrix_a1 = Album.create!(title: "The Jimi Hendrix Experience", year: 1968, artist_id: jimiHendrix.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/theJimiHendrixExperience.jpg" )
  theRollingStones_a1 = Album.create!(title: "Paint, It Black", year: 1966, artist_id: theRollingStones.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/paintItBlack.jpg" )
  queen_a1 = Album.create!(title: "News of the World", year: 1977, artist_id: queen.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/newsOfTheWorld.jpg" )
  biggieSmalls_a1 = Album.create!(title: "Ready to Die", year: 1994, artist_id: biggieSmalls.id, photo: "https://s3-us-west-1.amazonaws.com/modify-dev/readyToDie.jpg" )





  Song.destroy_all
  eminem_s1 = Song.create!(title: "When I'm Gone", year: 2005, genre: "Hip Hop", album_id: eminem_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/eminem-1", duration: "5:20" )
  linkinPark_s1 = Song.create!(title: "In the End", year: 2001, genre: "Nu Metal", album_id: linkinPark_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/linkinPark-1", duration: "3:37" )
  royOrbison_s1 = Song.create!(title: "Oh, Pretty Woman", year: 1964, genre: "Rock", album_id: royOrbison_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/royOrbison-1", duration: "2:57" )
  vanillaIce_s1 = Song.create!(title: "Ice Ice Baby", year: 1989, genre: "Hip Hop", album_id: vanillaIce_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/vanillaIce-1", duration: "4:01" )
  katyPerry_s1 = Song.create!(title: "I Kissed a Girl", year: 2008, genre: "Pop Rock", album_id: katyPerry_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/katyPerry-1", duration: "3:53" )
  ladyGaga_s1 = Song.create!(title: "Poker Face", year: 2008, genre: "Pop", album_id: ladyGaga_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/ladyGaga-1", duration: "3:35" )
  aHa_s1 = Song.create!(title: "Take on Me", year: 1984, genre: "Synthpop", album_id: aHa_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/aHa-1", duration: "3:47" )
  backStreetBoys_s1 = Song.create!(title: "I want it that Way", year: 1998, genre: "Pop", album_id: backStreetBoys_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/backstreetBoys-1", duration: "3:39" )
  justinBieber_s1 = Song.create!(title: "Sorry", year: 2015, genre: "Pop", album_id: justinBieber_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/justinBieber-1", duration: "3:25" )
  elvisPresley_s1 = Song.create!(title: "Hound Dog", year: 1952, genre: "Blues", album_id: elvisPresley_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/elvisPresley-1", duration: "2:43" )
  boyz2Men_s1 = Song.create!(title: "I'll make love to you", year: 1994, genre: "R&B", album_id: boyz2Men_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/boyz2Men-1", duration: "3:57" )
  theKillers_s1 = Song.create!(title: "Mr. Brightside", year: 2003, genre: "Alternative-Rock", album_id: theKillers_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/theKillers-1", duration: "3:42" )
  louisArmstrong_s1 = Song.create!(title: "What a Wonderful World", year: 1967, genre: "Jazz", album_id: louisArmstrong_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/louisArmstrong-1", duration: "2:17" )
  daftPunk_s1 = Song.create!(title: "Get Lucky", year: 2012, genre: "Disco", album_id: daftPunk_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/daftPunk-1", duration: "4:08" )
  rihanna_s1 = Song.create!(title: "Umbrella", year: 2007, genre: "Pop", album_id: rihanna_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/rihanna-1", duration: "4:13" )
  beyonce_s1 = Song.create!(title: "Single Ladies", year: 2008, genre: "Pop", album_id: beyonce_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/beyonce%CC%81-1", duration: "3:55" )
  theEagles_s1 = Song.create!(title: "Hotel California", year: 1976, genre: "Rock", album_id: theEagles_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/theEagles-1", duration: "6:30" )
  ledZeppelin_s1 = Song.create!(title: "Stairway to Heaven", year: 1971, genre: "Rock", album_id: ledZeppelin_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/ledZeppelin-1", duration: "8:02" )
  whitneyHouston_s1 = Song.create!(title: "I Wanna Dance with Somebody", year: 1987, genre: "Pop", album_id: whitneyHouston_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/whitneyHouston-1", duration: "4:53" )
  tupac_s1 = Song.create!(title: "California Love", year: 1995, genre: "Rap", album_id: tupac_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/tupac-1", duration: "4:45" )
  bobMarley_s1 = Song.create!(title: "One Love", year: 1977, genre: "Reggae", album_id: bobMarley_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/bobMarley-1", duration: "2:45" )
  katyPerry_s2 = Song.create!(title: "Firework", year: 2010, genre: "Pop", album_id: katyPerry_a2.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/katyPerry-2", duration: "3:53" )
  michaelJackson_s1 = Song.create!(title: "Thriller", year: 1982, genre: "Pop", album_id: michaelJackson_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson-1", duration: "4:55" )
  thePolice_s1 = Song.create!(title: "Every Breath You Take", year: 1983, genre: "Rock", album_id: thePolice_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/thePolice-1", duration: "3:55" )
  mcHammer_s1 = Song.create!(title: "U Can't Touch This", year: 1989, genre: "Hip Hop", album_id: mcHammer_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/mcHammer-1", duration: "4:17" )
  wizKhalifa_s1 = Song.create!(title: "See You Again", year: 2015, genre: "Hip Hop", album_id: wizKhalifa_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/wizKhalifa-1", duration: "3:57" )
  eminem_s2 = Song.create!(title: "My Name Is", year: 1999, genre: "Hip Hop", album_id: eminem_a2.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/eminem-2", duration: "4:28" )
  survivor_s1 = Song.create!(title: "Eye of the Tiger", year: 1982, genre: "Rock", album_id: survivor_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/survivor-1", duration: "4:10" )
  theBlackEyedPeas_s1 = Song.create!(title: "I Got a Feeling", year: 2009, genre: "Pop", album_id: theBlackEyedPeas_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/theBlackEyedPeas-1", duration: "4:48" )
  kellyClarkson_s1 = Song.create!(title: "Since You've been Gone", year: 2004, genre: "Pop", album_id: kellyClarkson_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/kellyClarkson-1", duration: "3:08" )
  adele_s1 = Song.create!(title: "Rolling in the Deep", year: 2010, genre: "Pop", album_id: adele_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/adele-1", duration: "3:53" )
  arethaFranklin_s1 = Song.create!(title: "Respect", year: 1967, genre: "Soul", album_id: arethaFranklin_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/arethaFranklin-1", duration: "2:29" )
  theBeatles_s1 = Song.create!(title: "I Wanna Hold Your Hand", year: 1963, genre: "Rock", album_id: theBeatles_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/theBeatles-1", duration: "2:25" )
  pharrellWilliams_s1 = Song.create!(title: "Happy", year: 2013, genre: "Soul", album_id: pharrellWilliams_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/pharrellWilliams-1", duration: "4:00" )
  beyonce_s2 = Song.create!(title: "Crazy in Love", year: 2003, genre: "Hip Hop", album_id: beyonce_a2.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/beyonce%CC%81-1", duration: "3:55" )
  luisFonsi_s1 = Song.create!(title: "Despacito", year: 2017, genre: "Latin Pop", album_id: luisFonsi_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/luisFonsi-1", duration: "4:41" )
  spiceGirls_s1 = Song.create!(title: "Wannabe", year: 1996, genre: "Pop", album_id: spiceGirls_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/spiceGirls-1", duration: "2:55" )
  gunsNRoses_s1 = Song.create!(title: "Sweet Child of Mine", year: 1988, genre: "Rock", album_id: gunsNRoses_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/gunsNRoses-1", duration: "" )
  markRonson_s1 = Song.create!(title: "Uptown Funk", year: 2014, genre: "Funk", album_id: markRonson_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/markRonson-1", duration: "4:31" )
  whitneyHouston_s2 = Song.create!(title: "I will Always Love You", year: 1974, genre: "Country", album_id: whitneyHouston_a2.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/whitneyHouston-2", duration: "4:28" )
  celineDion_s1 = Song.create!(title: "My Heart will Go On", year: 1997, genre: "Pop", album_id: celineDion_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/celineDion-1", duration: "4:37" )
  eminem_s3 = Song.create!(title: "Lose Yourself", year: 2002, genre: "Hip Hop", album_id: eminem_a3.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/eminem-1", duration: "5:20" )
  outkast_s1 = Song.create!(title: "Hey Ya!", year: 2003, genre: "Soul", album_id: outkast_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/outkast-1", duration: "3:55" )
  journey_s1 = Song.create!(title: "Don't Stop Believin'", year: 1981, genre: "Rock", album_id: journey_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/journey-1", duration: "4:10" )
  nirvana_s1 = Song.create!(title: "Smells Like Teen Spirit", year: 1991, genre: "Grunge", album_id: nirvana_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/nirvana-1", duration: "4:37" )
  beeGees_s1 = Song.create!(title: "Stayin Alive", year: 1977, genre: "Disco", album_id: beeGees_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/beeGees-1", duration: "4:02" )
  britneySpears_s1 = Song.create!(title: "...Baby One More Time", year: 1998, genre: "Pop", album_id: britneySpears_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/britneySpears-1", duration: "3:31" )
  michaelJackson_s2 = Song.create!(title: "Billie Jean", year: 1983, genre: "Disco", album_id: michaelJackson_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson-1", duration: "4:55" )
  theBeatles_s2 = Song.create!(title: "Hey Jude", year: 1968, genre: "Rock", album_id: theBeatles_a2.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/theBeatles-2", duration: "7:05" )
  acdc_s1 = Song.create!(title: "Highway to hell", year: 1978, genre: "Rock", album_id: acdc_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/acdc-1", duration: "3:27" )
  jimiHendrix_s1 = Song.create!(title: "All Along the Watchtower", year: 1968, genre: "Rock", album_id: jimiHendrix_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/jimiHendrix-1", duration: "4:01" )
  theRollingStones_s1 = Song.create!(title: "Paint it Black", year: 1966, genre: "Rock", album_id: theRollingStones_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/theRollingStones-1", duration: "3:46" )
  michaelJackson_s3 = Song.create!(title: "Beat It", year: 1983, genre: "Rock", album_id: michaelJackson_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson-3", duration: "4:18" )
  queen_s1 = Song.create!(title: "We Will Rock You", year: 1977, genre: "Rock", album_id: queen_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/queen-1", duration: "2:02" )
  biggieSmalls_s1 = Song.create!(title: "Juicy", year: 1994, genre: "Rap", album_id: biggieSmalls_a1.id, song: "https://s3-us-west-1.amazonaws.com/modify-dev/biggieSmalls-1", duration: "4:10" )

  # Playlist.destroy_all
  # rock = Playlist.create!
end