# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require "open-uri";

ActiveRecord::Base.transaction do
  
  User.destroy_all
  demo1 = User.create!(email: 'young1@gmail.com', password: 'password')
  demo2 = User.create!(email: 'young2@gmail.com', password: 'password')
  demo3 = User.create!(email: 'young3@gmail.com', password: 'password')
  demo4 = User.create!(email: 'young4@gmail.com', password: 'password')
  demo5 = User.create!(email: 'young5@gmail.com', password: 'password')




  Artist.destroy_all
  eminem = Artist.create!(name: "Eminem", biography: "bio")
  linkinPark = Artist.create!(name: "Linkin Park", biography: "bio")
  royOrbison = Artist.create!(name: "Ray Orbison", biography: "bio")
  vanillaIce = Artist.create!(name: "Vanilla Ice", biography: "bio")
  katyPerry = Artist.create!(name: "Katy Perry", biography: "bio")
  ladyGaga = Artist.create!(name: "Lady Gaga", biography: "bio")
  aHa = Artist.create!(name: "A-Ha", biography: "bio")
  backStreetBoys = Artist.create!(name: "Backstreet Boys", biography: "bio")
  justinBieber = Artist.create!(name: "Justin Bieber", biography: "bio")
  # elvisPresley = Artist.create!(name: "Elvis Presley", biography: "bio")
  # boyz2Men = Artist.create!(name: "Boyz 2 Men", biography: "bio")
  # theKillers = Artist.create!(name: "The Killers", biography: "bio")
  # louisArmstrong = Artist.create!(name: "Louis Armstrong", biography: "bio")
  # daftPunk = Artist.create!(name: "Daft Punk", biography: "bio")
  # rihanna = Artist.create!(name: "Rihanna", biography: "bio")
  # beyonce = Artist.create!(name: "Beyonce", biography: "bio")
  # theEagles = Artist.create!(name: "The Eagles", biography: "bio")
  # ledZeppelin = Artist.create!(name: "Led Zeppelin", biography: "bio")
  # whitneyHouston = Artist.create!(name: "Whitney Houston", biography: "bio")
  # tupac = Artist.create!(name: "Tupac", biography: "bio")
  # bobMarley = Artist.create!(name: "Bob Marley", biography: "bio")
  # michaelJackson = Artist.create!(name: "Michael Jackson", biography: "bio")
  # thePolice = Artist.create!(name: "The Police", biography: "bio")
  # mcHammer = Artist.create!(name: "MC Hammer", biography: "bio")
  # wizKhalifa = Artist.create!(name: "Wiz Khalifa", biography: "bio")
  # survivor = Artist.create!(name: "Survivor", biography: "bio")
  # theBlackEyedPeas = Artist.create!(name: "The Black Eyed Peas", biography: "bio")
  # kellyClarkson = Artist.create!(name: "Kelly Clarkson", biography: "bio")
  # adele = Artist.create!(name: "Adele", biography: "bio")
  # arethaFranklin = Artist.create!(name: "Aretha Franklin", biography: "bio")
  # theBeatles = Artist.create!(name: "The Beatles", biography: "bio")
  # pharrellWilliams = Artist.create!(name: "Pharrell Williams", biography: "bio")
  # luisFonsi = Artist.create!(name: "Luis Fonsi", biography: "bio")
  # spiceGirls = Artist.create!(name: "Spice Girls", biography: "bio")
  # gunsNRoses = Artist.create!(name: "Guns N Roses", biography: "bio")
  # markRonson = Artist.create!(name: "Mark Ronson", biography: "bio")
  # celineDion = Artist.create!(name: "Celine Dion", biography: "bio")
  # outkast = Artist.create!(name: "Outkast", biography: "bio")
  # journey = Artist.create!(name: "Journey", biography: "bio")
  # nirvana = Artist.create!(name: "Nirvana", biography: "bio")
  # beeGees = Artist.create!(name: "Bee Gees", biography: "bio")
  # britneySpears = Artist.create!(name: "Britney Spears", biography: "bio")
  # acdc = Artist.create!(name: "ACDC", biography: "bio")
  # jimiHendrix = Artist.create!(name: "Jimi Hendrix", biography: "bio")
  # theRollingStones = Artist.create!(name: "The Rolling Stones", biography: "bio")
  # queen = Artist.create!(name: "Queen", biography: "bio")
  # biggieSmalls = Artist.create!(name: "Biggie Smalls", biography: "bio")
  


  # , photo: {io: open(""), filename: ""}

                # @@@@@@@@@@@@@@            TRYING TO UNDO             @@@@@@@@@@@@@@
  # elvisPresley_a1 = Album.create!(title: "Night Mare", year: 1952, artist_id: elvisPresley.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/nightMare.jpg"), filename: "nightMare"})
  # boyz2Men_a1 = Album.create!(title: "II", year: 1994, artist_id: boyz2Men.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/II.jpg"), filename: "II"})
  # theKillers_a1 = Album.create!(title: "Smile Like You Mean It", year: 2003, artist_id: theKillers.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/smileLikeYouMeanIt.jpg"), filename: "smileLikeYouMeanIt"})
  # louisArmstrong_a1 = Album.create!(title: "Cabaret", year: 1967, artist_id: louisArmstrong.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/cabaret.jpg"), filename: "cabaret"})
  # daftPunk_a1 = Album.create!(title: "Random Access Memories", year: 2012, artist_id: daftPunk.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/randomAccessMemories.jpg"), filename: "randomAccessMemories"})
  # rihanna_a1 = Album.create!(title: "Good Girl Gone Bad", year: 2007, artist_id: rihanna.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/goodGirlGoneBad.jpg"), filename: "goodGirlGoneBad"})
  # beyonce_a1 = Album.create!(title: "I Am... Sash Fierce", year: 2008, artist_id: beyonce.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/iAmSashFierce.jpg"), filename: "iAmSashFierce"})
  # theEagles_a1 = Album.create!(title: "Hotel California", year: 1976, artist_id: theEagles.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/hotelCalifornia.jpg"), filename: "hotelCalifornia"})
  # ledZeppelin_a1 = Album.create!(title: "Led Zeppelin IV", year: 1971, artist_id: ledZeppelin.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/ledZeppelinIV.jpg"), filename: "ledZeppelinIV"})




  Album.destroy_all
  eminem_a1 = Album.create!(title: "Curtain Call", year: 2005, artist_id: eminem.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/curtainCall.png"), filename: "curtainCall"})
  linkinPark_a1 = Album.create!(title: "Hybrid Theory", year: 2001, artist_id: linkinPark.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/hybridTheory.jpg"), filename: "hybridTheory"})
  royOrbison_a1 = Album.create!(title: "Yo te Amo Maria", year: 1964, artist_id: royOrbison.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/yoTeAmoMaria.jpg"), filename: "yoTeAmoMaria"})
  vanillaIce_a1 = Album.create!(title: "Play That Funky Music", year: 1989, artist_id: vanillaIce.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/playThatFunkyMusic.jpg"), filename: "playThatFunkyMusic"})
  katyPerry_a1 = Album.create!(title: "One of the Boys", year: 2008, artist_id: katyPerry.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/oneOfTheBoys.jpg"), filename: "oneOfTheBoys"})
  ladyGaga_a1 = Album.create!(title: "The Fame", year: 2008, artist_id: ladyGaga.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theFame.jpg"), filename: "theFame"})
  aHa_a1 = Album.create!(title: "Hunting High and Low", year: 1984, artist_id: aHa.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/huntingHighAndLow.jpg"), filename: "huntingHighAndLow"})
  backStreetBoys_a1 = Album.create!(title: "Millennium", year: 1998, artist_id: backStreetBoys.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/millennium.jpg"), filename: "millennium"})
  justinBieber_a1 = Album.create!(title: "Purpose", year: 2015, artist_id: justinBieber.id, photo: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/purpose.jpg"), filename: "purpose"})
  ## elvisPresley_a1 = Album.create!(title: "Night Mare", year: 1952, artist_id: elvisPresley.id, photo: {io: open(""), filename: ""})
  ## boyz2Men_a1 = Album.create!(title: "II", year: 1994, artist_id: boyz2Men.id, photo: {io: open(""), filename: ""})
  ## theKillers_a1 = Album.create!(title: "Smile Like You Mean It", year: 2003, artist_id: theKillers.id, photo: {io: open(""), filename: ""})
  ## louisArmstrong_a1 = Album.create!(title: "Cabaret", year: 1967, artist_id: louisArmstrong.id, photo: {io: open(""), filename: ""})
  ## daftPunk_a1 = Album.create!(title: "Random Access Memories", year: 2012, artist_id: daftPunk.id, photo: {io: open(""), filename: ""})
  ## rihanna_a1 = Album.create!(title: "Good Girl Gone Bad", year: 2007, artist_id: rihanna.id, photo: {io: open(""), filename: ""})
  ## beyonce_a1 = Album.create!(title: "I Am... Sash Fierce", year: 2008, artist_id: beyonce.id, photo: {io: open(""), filename: ""})
  ## theEagles_a1 = Album.create!(title: "Hotel California", year: 1976, artist_id: theEagles.id, photo: {io: open(""), filename: ""})
  ## ledZeppelin_a1 = Album.create!(title: "Led Zeppelin IV", year: 1971, artist_id: ledZeppelin.id, photo: {io: open(""), filename: ""})
  # whitneyHouston_a1 = Album.create!(title: "Whitney", year: 1987, artist_id: whitneyHouston.id, photo: {io: open(""), filename: ""})
  # tupac_a1 = Album.create!(title: "All Eyez on Me", year: 1995, artist_id: tupac.id, photo: {io: open(""), filename: ""})
  # bobMarley_a1 = Album.create!(title: "Exodus", year: 1977, artist_id: bobMarley.id, photo: {io: open(""), filename: ""})
  # katyPerry_a2 = Album.create!(title: "Teenage Dream", year: 2010, artist_id: katyPerry.id, photo: {io: open(""), filename: ""})
  # michaelJackson_a1 = Album.create!(title: "Thriller", year: 1982, artist_id: michaelJackson.id, photo: {io: open(""), filename: ""})
  # thePolice_a1 = Album.create!(title: "Synchronicity", year: 1983, artist_id: thePolice.id, photo: {io: open(""), filename: ""})
  # mcHammer_a1 = Album.create!(title: "Please Hammer, Don't Hurt 'Em", year: 1989, artist_id: mcHammer.id, photo: {io: open(""), filename: ""})
  # wizKhalifa_a1 = Album.create!(title: "Nine Track Mind", year: 2015, artist_id: wizKhalifa.id, photo: {io: open(""), filename: ""})
  # eminem_a2 = Album.create!(title: "The Slim Shady LP", year: 1999, artist_id: eminem.id, photo: {io: open(""), filename: ""})
  # survivor_a1 = Album.create!(title: "Eye of the Tiger", year: 1982, artist_id: survivor.id, photo: {io: open(""), filename: ""})
  # theBlackEyedPeas_a1 = Album.create!(title: "The E.N.D.", year: 2009, artist_id: theBlackEyedPeas.id, photo: {io: open(""), filename: ""})
  # kellyClarkson_a1 = Album.create!(title: "Breakaway", year: 2004, artist_id: kellyClarkson.id, photo: {io: open(""), filename: ""})
  # adele_a1 = Album.create!(title: "21", year: 2010, artist_id: adele.id, photo: {io: open(""), filename: ""})
  # arethaFranklin_a1 = Album.create!(title: "I Never Loved a Man the Way I Love You", year: 1967, artist_id: arethaFranklin.id, photo: {io: open(""), filename: ""})
  # theBeatles_a1 = Album.create!(title: "Meet the Beatles", year: 1963, artist_id: theBeatles.id, photo: {io: open(""), filename: ""})
  # pharrellWilliams_a1 = Album.create!(title: "Girl", year: 2013, artist_id: pharrellWilliams.id, photo: {io: open(""), filename: ""})
  # beyonce_a2 = Album.create!(title: "Dangerously in Love", year: 2003, artist_id: beyonce.id, photo: {io: open(""), filename: ""})
  # luisFonsi_a1 = Album.create!(title: "Vida", year: 2017, artist_id: luisFonsi.id, photo: {io: open(""), filename: ""})
  # spiceGirls_a1 = Album.create!(title: "Spice", year: 1996, artist_id: spiceGirls.id, photo: {io: open(""), filename: ""})
  # gunsNRoses_a1 = Album.create!(title: "Appetite for Desctruction", year: 1988, artist_id: gunsNRoses.id, photo: {io: open(""), filename: ""})
  # markRonson_a1 = Album.create!(title: "Uptown Special", year: 2014, artist_id: markRonson.id, photo: {io: open(""), filename: ""})
  # whitneyHouston_a2 = Album.create!(title: "Jolene", year: 1974, artist_id: whitneyHouston.id, photo: {io: open(""), filename: ""})
  # celineDion_a1 = Album.create!(title: "Let's Talk About Love", year: 1997, artist_id: celineDion.id, photo: {io: open(""), filename: ""})
  # eminem_a3 = Album.create!(title: "8 Mile", year: 2002, artist_id: eminem.id, photo: {io: open(""), filename: ""})
  # outkast_a1 = Album.create!(title: "Speakerboxxx/The Love Below", year: 2003, artist_id: outkast.id, photo: {io: open(""), filename: ""})
  # journey_a1 = Album.create!(title: "Escape", year: 1981, artist_id: journey.id, photo: {io: open(""), filename: ""})
  # nirvana_a1 = Album.create!(title: "Nevermind", year: 1991, artist_id: nirvana.id, photo: {io: open(""), filename: ""})
  # beeGees_a1 = Album.create!(title: "Saturday Night Fever", year: 1977, artist_id: beeGees.id, photo: {io: open(""), filename: ""})
  # britneySpears_a1 = Album.create!(title: "...Baby One More Time", year: 1998, artist_id: britneySpears.id, photo: {io: open(""), filename: ""})
  # theBeatles_a2 = Album.create!(title: "Revolution", year: 1968, artist_id: theBeatles.id, photo: {io: open(""), filename: ""})
  # acdc_a1 = Album.create!(title: "Highway to Hell", year: 1978, artist_id: acdc.id, photo: {io: open(""), filename: ""})
  # jimiHendrix_a1 = Album.create!(title: "John Wesley Harding", year: 1968, artist_id: jimiHendrix.id, photo: {io: open(""), filename: ""})
  # theRollingStones_a1 = Album.create!(title: "Stupid Girl", year: 1966, artist_id: theRollingStones.id, photo: {io: open(""), filename: ""})
  # queen_a1 = Album.create!(title: "News of the World", year: 1977, artist_id: queen.id, photo: {io: open(""), filename: ""})
  # biggieSmalls_a1 = Album.create!(title: "Ready to Die", year: 1994, artist_id: biggieSmalls.id, photo: {io: open(""), filename: ""})





  Song.destroy_all
  eminem_s1 = Song.create!(title: "When I'm Gone", year: 2005, genre: "Hip Hop", album_id: eminem_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/eminem-1"), filename: "eminem-s1"})
  linkinPark_s1 = Song.create!(title: "In the End", year: 2001, genre: "Nu Metal", album_id: linkinPark_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/linkinPark-1"), filename: "linkinPark-s1"})
  royOrbison_s1 = Song.create!(title: "Oh, Pretty Woman", year: 1964, genre: "Rock", album_id: royOrbison_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/royOrbison-1"), filename: "royOrbison-s1"})
  vanillaIce_s1 = Song.create!(title: "Ice Ice Baby", year: 1989, genre: "Hip Hop", album_id: vanillaIce_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/vanillaIce-1"), filename: "vanillaIce-s1"})
  katyPerry_s1 = Song.create!(title: "I Kissed a Girl", year: 2008, genre: "Pop Rock", album_id: katyPerry_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/katyPerry-1"), filename: "katyPerry-s1"})
  ladyGaga_s1 = Song.create!(title: "Poker Face", year: 2008, genre: "Pop", album_id: ladyGaga_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/ladyGaga-1"), filename: "ladyGaga-s1"})
  aHa_s1 = Song.create!(title: "Take on Me", year: 1984, genre: "Synthpop", album_id: aHa_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/aHa-1"), filename: "aHa-s1"})
  backStreetBoys_s1 = Song.create!(title: "I want it that Way", year: 1998, genre: "Pop", album_id: backStreetBoys_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/backstreetBoys-1"), filename: "backstreetBoys-s1"})
  justinBieber_s1 = Song.create!(title: "Sorry", year: 2015, genre: "Pop", album_id: justinBieber_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/justinBieber-1"), filename: "justinBieber-s1"})
  # elvisPresley_s1 = Song.create!(title: "Hound Dog", year: 1952, genre: "Blues", album_id: elvisPresley_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/elvisPresley-1"), filename: "elvisPresley-s1"})
  # boyz2Men_s1 = Song.create!(title: "I'll make love to you", year: 1994, genre: "R&B", album_id: boyz2Men_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/boyz2Men-1"), filename: "boyz2Men-s1"})
  # theKillers_s1 = Song.create!(title: "Mr. Brightside", year: 2003, genre: "Alternative-Rock", album_id: theKillers_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theKillers-1"), filename: "theKillers-s1"})
  # louisArmstrong_s1 = Song.create!(title: "What a Wonderful World", year: 1967, genre: "Jazz", album_id: louisArmstrong_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/louisArmstrong-1"), filename: "louisArmstrong-s1"})
  # daftPunk_s1 = Song.create!(title: "Get Lucky", year: 2012, genre: "Disco", album_id: daftPunk_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/daftPunk-1"), filename: "daftPunk-s1"})
  # rihanna_s1 = Song.create!(title: "Umbrella", year: 2007, genre: "Pop", album_id: rihanna_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/rihanna-1"), filename: "rihana-s1"})
  # beyonce_s1 = Song.create!(title: "Single Ladies", year: 2008, genre: "Pop", album_id: beyonce_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/beyonce%CC%81-1"), filename: "beyonce-s1"})
  # theEagles_s1 = Song.create!(title: "Hotel California", year: 1976, genre: "Rock", album_id: theEagles_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theEagles-1"), filename: "theEagles-s1"})
  # ledZeppelin_s1 = Song.create!(title: "Stairway to Heaven", year: 1971, genre: "Rock", album_id: ledZeppelin_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/ledZeppelin-1"), filename: "ledZeppelin-s1"})
  # whitneyHouston_s1 = Song.create!(title: "I Wanna Dance with Somebody", year: 1987, genre: "Pop", album_id: whitneyHouston_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/whitneyHouston-1"), filename: "whitneyHouston-s1"})
  # tupac_s1 = Song.create!(title: "California Love", year: 1995, genre: "Rap", album_id: tupac_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/tupac-1"), filename: "tupac-s1"})
  # bobMarley_s1 = Song.create!(title: "One Love", year: 1977, genre: "Reggae", album_id: bobMarley_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/bobMarley-1"), filename: "bobMarley-s1"})
  # katyPerry_s2 = Song.create!(title: "Firework", year: 2010, genre: "Pop", album_id: katyPerry_a2.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/katyPerry-2"), filename: "katyPerry-s2"})
  # michaelJackson_s1 = Song.create!(title: "Thriller", year: 1982, genre: "Pop", album_id: michaelJackson_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson-1"), filename: "michaelJackson-s1"})
  # thePolice_s1 = Song.create!(title: "Every Breath You Take", year: 1983, genre: "Rock", album_id: thePolice_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/thePolice-1"), filename: "thePolice-s1"})
  # mcHammer_s1 = Song.create!(title: "U Can't Touch This", year: 1989, genre: "Hip Hop", album_id: mcHammer_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/mcHammer-1"), filename: "mcHammer-s1"})
  # wizKhalifa_s1 = Song.create!(title: "See You Again", year: 2015, genre: "Hip Hop", album_id: wizKhalifa_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/wizKhalifa-1"), filename: "wizKhalifa-s1"})
  # eminem_s2 = Song.create!(title: "My Name Is", year: 1999, genre: "Hip Hop", album_id: eminem_a2.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/eminem-2"), filename: "eminem-s2"})
  # survivor_s1 = Song.create!(title: "Eye of the Tiger", year: 1982, genre: "Rock", album_id: survivor_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/survivor-1"), filename: "survivor-s1"})
  # theBlackEyedPeas_s1 = Song.create!(title: "I Got a Feeling", year: 2009, genre: "Pop", album_id: theBlackEyedPeas_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theBlackEyedPeas-1"), filename: "theBlackEyedPeas-s1"})
  # kellyClarkson_s1 = Song.create!(title: "Since You've been Gone", year: 2004, genre: "Pop", album_id: kellyClarkson_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/kellyClarkson-1"), filename: "kellyClarkson-s1"})
  # adele_s1 = Song.create!(title: "Rolling in the Deep", year: 2010, genre: "Pop", album_id: adele_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/adele-1"), filename: "adele-s1"})
  # arethaFranklin_s1 = Song.create!(title: "Respect", year: 1967, genre: "Soul", album_id: arethaFranklin_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/arethaFranklin-1"), filename: "arethaFranklin-s1"})
  # theBeatles_s1 = Song.create!(title: "I Wanna Hold Your Hand", year: 1963, genre: "Rock", album_id: theBeatles_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theBeatles-1"), filename: "theBeatles-s1"})
  # pharrellWilliams_s1 = Song.create!(title: "Happy", year: 2013, genre: "Soul", album_id: pharrellWilliams_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/pharrellWilliams-1"), filename: "pharrellWilliams-s1"})
  # beyonce_s2 = Song.create!(title: "Crazy in Love", year: 2003, genre: "Hip Hop", album_id: beyonce_a2.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/beyonce%CC%81-1"), filename: "beyonce-s2"})
  # luisFonsi_s1 = Song.create!(title: "Despacito", year: 2017, genre: "Latin Pop", album_id: luisFonsi_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/luisFonsi-1"), filename: "luisFonsi-s1"})
  # spiceGirls_s1 = Song.create!(title: "Wannabe", year: 1996, genre: "Pop", album_id: spiceGirls_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/spiceGirls-1"), filename: "spiceGirls-s1"})
  # gunsNRoses_s1 = Song.create!(title: "Sweet Child of Mine", year: 1988, genre: "Rock", album_id: gunsNRoses_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/gunsNRoses-1"), filename: "gunsNRoses-s1"})
  # markRonson_s1 = Song.create!(title: "Uptown Funk", year: 2014, genre: "Funk", album_id: markRonson_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/markRonson-1"), filename: "markRonson-s1"})
  # whitneyHouston_s2 = Song.create!(title: "I will Always Love You", year: 1974, genre: "Country", album_id: whitneyHouston_a2.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/whitneyHouston-2"), filename: "whitneyHouston-s2"})
  # celineDion_s1 = Song.create!(title: "My Heart will Go On", year: 1997, genre: "Pop", album_id: celineDion_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/celineDion-1"), filename: "celineDion-s1"})
  # eminem_s3 = Song.create!(title: "Lose Yourself", year: 2002, genre: "Hip Hop", album_id: eminem_a3.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/eminem-1"), filename: "eminem-s3"})
  # outkast_s1 = Song.create!(title: "Hey Ya!", year: 2003, genre: "Soul", album_id: outkast_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/outkast-1"), filename: "outkast-s1"})
  # journey_s1 = Song.create!(title: "Don't Stop Believin'", year: 1981, genre: "Rock", album_id: journey_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/journey-1"), filename: "journey-s1"})
  # nirvana_s1 = Song.create!(title: "Smells Like Teen Spirit", year: 1991, genre: "Grunge", album_id: nirvana_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/nirvana-1"), filename: "nirvana-s1"})
  # beeGees_s1 = Song.create!(title: "Stayin Alive", year: 1977, genre: "Disco", album_id: beeGees_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/beeGees-1"), filename: "beeGees-s1"})
  # britneySpears_s1 = Song.create!(title: "...Baby One More Time", year: 1998, genre: "Pop", album_id: britneySpears_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/britneySpears-1"), filename: "britneySpears-s1"})
  # michaelJackson_s2 = Song.create!(title: "Billie Jean", year: 1983, genre: "Disco", album_id: michaelJackson_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson-1"), filename: "michaelJackson-s2"})
  # theBeatles_s2 = Song.create!(title: "Hey Jude", year: 1968, genre: "Rock", album_id: theBeatles_a2.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theBeatles-2"), filename: "theBeatles-s2"})
  # acdc_s1 = Song.create!(title: "Highway to hell", year: 1978, genre: "Rock", album_id: acdc_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/acdc-1"), filename: "acdc-s1"})
  # jimiHendrix_s1 = Song.create!(title: "All Along the Watchtower", year: 1968, genre: "Rock", album_id: jimiHendrix_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/jimiHendrix-1"), filename: "jimiHendrix-s1"})
  # theRollingStones_s1 = Song.create!(title: "Paint it Black", year: 1966, genre: "Rock", album_id: theRollingStones_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/theRollingStones-1"), filename: "theRollingStones-s1"})
  # michaelJackson_s3 = Song.create!(title: "Beat It", year: 1983, genre: "Rock", album_id: michaelJackson_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/michaelJackson-3"), filename: "michaelJackson-s3"})
  # queen_s1 = Song.create!(title: "We Will Rock You", year: 1977, genre: "Rock", album_id: queen_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/queen-1"), filename: "queen-s3"})
  # biggieSmalls_s1 = Song.create!(title: "Juicy", year: 1994, genre: "Rap", album_id: biggieSmalls_a1.id, song: {io: open("https://s3-us-west-1.amazonaws.com/modify-dev/biggieSmalls-1"), filename: "biggieSmalls-s3"})

  # Playlist.destroy_all
  # rock = Playlist.create!
end